// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-axios';
import type { TracksGetTracksData, TracksGetTracksError, TracksGetTracksResponse, TracksSearchTracksData, TracksSearchTracksError, TracksSearchTracksResponse, TracksGetTrackData, TracksGetTrackError, TracksGetTrackResponse, AuthGetInitDataError, AuthGetInitDataResponse, UserGetPlaylistsData, UserGetPlaylistsError, UserGetPlaylistsResponse, PlaylistsCreatePlaylistData, PlaylistsCreatePlaylistError, PlaylistsCreatePlaylistResponse, PlaylistsGetPlaylistsData, PlaylistsGetPlaylistsError, PlaylistsGetPlaylistsResponse, PlaylistsGetPlaylistData, PlaylistsGetPlaylistError, PlaylistsGetPlaylistResponse, PlaylistsUpdatePlaylistData, PlaylistsUpdatePlaylistError, PlaylistsUpdatePlaylistResponse, PlaylistsRemovePlaylistData, PlaylistsRemovePlaylistError, PlaylistsRemovePlaylistResponse, PlaylistsAddTrackToPlaylistData, PlaylistsAddTrackToPlaylistError, PlaylistsAddTrackToPlaylistResponse, PlaylistsRemoveTrackFromPlaylistData, PlaylistsRemoveTrackFromPlaylistError, PlaylistsRemoveTrackFromPlaylistResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Get Tracks
 */
export const tracksGetTracks = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<TracksGetTracksData, ThrowOnError>) => {
    return (options?.client ?? client).get<TracksGetTracksResponse, TracksGetTracksError, ThrowOnError>({
        ...options,
        url: '/tracks/'
    });
};

/**
 * Search Tracks
 */
export const tracksSearchTracks = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<TracksSearchTracksData, ThrowOnError>) => {
    return (options?.client ?? client).get<TracksSearchTracksResponse, TracksSearchTracksError, ThrowOnError>({
        ...options,
        url: '/tracks/search'
    });
};

/**
 * Get Track
 */
export const tracksGetTrack = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<TracksGetTrackData, ThrowOnError>) => {
    return (options?.client ?? client).get<TracksGetTrackResponse, TracksGetTrackError, ThrowOnError>({
        ...options,
        url: '/tracks/{track_id}'
    });
};

/**
 * Get Init Data
 */
export const authGetInitData = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<AuthGetInitDataResponse, AuthGetInitDataError, ThrowOnError>({
        ...options,
        url: '/auth/init-data'
    });
};

/**
 * Get Playlists
 */
export const userGetPlaylists = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<UserGetPlaylistsData, ThrowOnError>) => {
    return (options?.client ?? client).get<UserGetPlaylistsResponse, UserGetPlaylistsError, ThrowOnError>({
        ...options,
        url: '/user/{user_id}/playlists'
    });
};

/**
 * Create Playlist
 */
export const playlistsCreatePlaylist = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<PlaylistsCreatePlaylistData, ThrowOnError>) => {
    return (options?.client ?? client).post<PlaylistsCreatePlaylistResponse, PlaylistsCreatePlaylistError, ThrowOnError>({
        ...options,
        url: '/playlists/'
    });
};

/**
 * Get Playlists
 */
export const playlistsGetPlaylists = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<PlaylistsGetPlaylistsData, ThrowOnError>) => {
    return (options?.client ?? client).get<PlaylistsGetPlaylistsResponse, PlaylistsGetPlaylistsError, ThrowOnError>({
        ...options,
        url: '/playlists/'
    });
};

/**
 * Get Playlist
 */
export const playlistsGetPlaylist = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<PlaylistsGetPlaylistData, ThrowOnError>) => {
    return (options?.client ?? client).get<PlaylistsGetPlaylistResponse, PlaylistsGetPlaylistError, ThrowOnError>({
        ...options,
        url: '/playlists/{playlist_id}'
    });
};

/**
 * Update Playlist
 */
export const playlistsUpdatePlaylist = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<PlaylistsUpdatePlaylistData, ThrowOnError>) => {
    return (options?.client ?? client).put<PlaylistsUpdatePlaylistResponse, PlaylistsUpdatePlaylistError, ThrowOnError>({
        ...options,
        url: '/playlists/{playlist_id}'
    });
};

/**
 * Remove Playlist
 */
export const playlistsRemovePlaylist = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<PlaylistsRemovePlaylistData, ThrowOnError>) => {
    return (options?.client ?? client).delete<PlaylistsRemovePlaylistResponse, PlaylistsRemovePlaylistError, ThrowOnError>({
        ...options,
        url: '/playlists/{playlist_id}'
    });
};

/**
 * Add Track To Playlist
 */
export const playlistsAddTrackToPlaylist = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<PlaylistsAddTrackToPlaylistData, ThrowOnError>) => {
    return (options?.client ?? client).post<PlaylistsAddTrackToPlaylistResponse, PlaylistsAddTrackToPlaylistError, ThrowOnError>({
        ...options,
        url: '/playlists/{playlist_id}/tracks'
    });
};

/**
 * Remove Track From Playlist
 */
export const playlistsRemoveTrackFromPlaylist = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<PlaylistsRemoveTrackFromPlaylistData, ThrowOnError>) => {
    return (options?.client ?? client).delete<PlaylistsRemoveTrackFromPlaylistResponse, PlaylistsRemoveTrackFromPlaylistError, ThrowOnError>({
        ...options,
        url: '/playlists/{playlist_id}/tracks/{track_id}'
    });
};