// This file is auto-generated by @hey-api/openapi-ts

export type app__schemas__playlist__Track = {
  id: string;
};

export type Track = {
  id: string;
  title: string;
  authors: Array<Author>;
  duration: number;
  source: string;
  thumbnail: string;
};

export type Author = {
  id: string;
  name: string;
  genres: string;
};

export type CreatePlaylist = {
  title: string;
  thumbnail?: string | null;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type Playlist = {
  title: string;
  thumbnail?: string | null;
  id: string;
};

export type Playlists = {
  playlists: Array<Playlist>;
};

export type PlaylistWithTracks = {
  title: string;
  thumbnail?: string | null;
  id: string;
  tracks: Array<app__schemas__playlist__Track>;
};

export type Track_Input = {
  id: string;
};

export type Tracks = {
  tracks: Array<Track>;
};

export type User = {
  id: string;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type TracksGetTracksData = {
  query?: {
    limit?: number;
    offset?: number;
  };
};

export type TracksGetTracksResponse = Tracks;

export type TracksGetTracksError = HTTPValidationError;

export type TracksSearchTracksData = {
  query: {
    limit?: number;
    offset?: number;
    query: string;
  };
};

export type TracksSearchTracksResponse = Tracks;

export type TracksSearchTracksError = HTTPValidationError;

export type TracksGetTrackData = {
  path: {
    track_id: string;
  };
};

export type TracksGetTrackResponse = Track;

export type TracksGetTrackError = HTTPValidationError;

export type AuthGetInitDataResponse = User;

export type AuthGetInitDataError = unknown;

export type UserGetPlaylistsData = {
  path: {
    user_id: string;
  };
};

export type UserGetPlaylistsResponse = Playlists;

export type UserGetPlaylistsError = HTTPValidationError;

export type PlaylistsCreatePlaylistData = {
  body: CreatePlaylist;
};

export type PlaylistsCreatePlaylistResponse = Playlist;

export type PlaylistsCreatePlaylistError = HTTPValidationError;

export type PlaylistsGetPlaylistsData = {
  query?: {
    limit?: number;
    offset?: number;
  };
};

export type PlaylistsGetPlaylistsResponse = Playlists;

export type PlaylistsGetPlaylistsError = HTTPValidationError;

export type PlaylistsGetPlaylistData = {
  path: {
    playlist_id: string;
  };
};

export type PlaylistsGetPlaylistResponse = PlaylistWithTracks;

export type PlaylistsGetPlaylistError = HTTPValidationError;

export type PlaylistsUpdatePlaylistData = {
  body: CreatePlaylist;
  path: {
    playlist_id: string;
  };
};

export type PlaylistsUpdatePlaylistResponse = Playlist;

export type PlaylistsUpdatePlaylistError = HTTPValidationError;

export type PlaylistsRemovePlaylistData = {
  path: {
    playlist_id: string;
  };
};

export type PlaylistsRemovePlaylistResponse = Playlist;

export type PlaylistsRemovePlaylistError = HTTPValidationError;

export type PlaylistsAddTrackToPlaylistData = {
  body: Track_Input;
  path: {
    playlist_id: string;
  };
};

export type PlaylistsAddTrackToPlaylistResponse = Playlist;

export type PlaylistsAddTrackToPlaylistError = HTTPValidationError;

export type PlaylistsRemoveTrackFromPlaylistData = {
  path: {
    playlist_id: string;
    track_id: string;
  };
};

export type PlaylistsRemoveTrackFromPlaylistResponse = Playlist;

export type PlaylistsRemoveTrackFromPlaylistError = HTTPValidationError;
