name: Code analysys

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  conventional_commit:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      -
        uses: webiny/action-conventional-commits@8bc41ff4e7d423d56fa4905f6ff79209a78776c7
  test:
    runs-on: ubuntu-latest
    needs: [conventional_commit]
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      -
        name: Install dependencies
        run: npm ci
      -
        name: Run Jest tests
        run: npm test
      -
        name: Upload coverage
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage/lcov.info
        env:
            CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349
      -
        name: Build
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75
        with:
          push: false
          tags: ${{ vars.DOCKER_NAMESPACE }}/${{ github.event.repository.name }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha,scope=${{ github.ref_name }}-image
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-image
